### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by TC-Wheel** [gwisk/gradguide#1]
Psych! 

This isn't an actually issue. This is a thank you for writing such an excellent guide. 
I am going to share this with anyone who asks. 
For people like me, who have no family members or close friends who've gone to graduate school- this is a godsend. 

Thank you. 

(You can close this issue now.)

**Comment by gwisk** [comment]
Hey! Of course, I'm so glad you found it helpful. Of course, if you have any questions or want to know more, feel free to email me! :) Take care!
